// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/adnanahmady/go-rest-api-blog/config"
	"github.com/adnanahmady/go-rest-api-blog/pkg/applog"
	"github.com/adnanahmady/go-rest-api-blog/pkg/database"
	"github.com/google/wire"
)

// Injectors from wire.go:

func WireUpApp() (*App, error) {
	configConfig := config.GetConfig()
	appLog := applog.NewLog(configConfig)
	databaseManagerImpl := database.NewDatabaseManager(configConfig, appLog)
	app := &App{
		Config:   configConfig,
		Logger:   appLog,
		Database: databaseManagerImpl,
	}
	return app, nil
}

// wire.go:

type App struct {
	Config   *config.Config
	Logger   *applog.AppLog
	Database *database.DatabaseManagerImpl
}

var AppSet = wire.NewSet(config.GetConfig, applog.NewLog, wire.Bind(new(applog.Logger), new(*applog.AppLog)), database.NewDatabaseManager, wire.Bind(new(database.DatabaseManager), new(*database.DatabaseManagerImpl)), wire.Struct(new(App), "*"))
